exports.seed = function (knex, Promise) {
  // Deletes ALL existing entries
  return knex("managers")
    .del()
    .then(function () {
      // Inserts seed entries
      return knex("managers").insert([
        {
          id: 1,
          manager: "Ben",
          team_name: "Barles Charkley",
          year_joined: "2007",
          seasons: "10",
          status: "Active",
          total_pts: "186737",
          total_w: "104",
          total_l: "52",
          games_played: "156",
          playoffs: "9",
          topfour: "9",
          finals: "4",
          titles: "2",
        },

        {
          id: 2,
          manager: "Jon",
          team_name: "Windy City Champs",
          year_joined: "2007",
          seasons: "10",
          status: "Active",
          total_pts: "191975",
          total_w: "106",
          total_l: "50",
          games_played: "156",
          playoffs: "7",
          topfour: "5",
          finals: "4",
          titles: "3",
        },
        {
          id: 3,
          manager: "Zettle",
          team_name: "Jesus Shuttlesworth",
          year_joined: "2007",
          seasons: "5",
          status: "Inactive",
          total_pts: "75736",
          total_w: "54",
          total_l: "21",
          games_played: "75",
          playoffs: "4",
          topfour: "1",
          finals: "0",
          titles: "0",
        },
        {
          id: 4,
          manager: "Yacine",
          team_name: "Frat So Hard",
          year_joined: "2007",
          seasons: "2",
          status: "Inactive",
          total_pts: "27914",
          total_w: "20",
          total_l: "14",
          games_played: "34",
          playoffs: "2",
          topfour: "1",
          finals: "0",
          titles: "0",
        },
        {
          id: 5,
          manager: "Brady",
          team_name: "H.H.L.D.",
          year_joined: "2007",
          seasons: "3",
          status: "Inactive",
          total_pts: "44401",
          total_w: "15",
          total_l: "19",
          games_played: "34",
          playoffs: "2",
          topfour: "0",
          finals: "0",
          titles: "0",
        },
        {

          id: 6,
          manager: "Breeden",
          team_name: "The Mau5Trap",
          year_joined: "2007",
          seasons: "3",
          status: "Inactive",
          total_pts: "25629",
          total_w: "10",
          total_l: "20",
          games_played: "32",
          playoffs: "1",
          topfour: "0",
          finals: "0",
          titles: "0",
        },
        {
          id: 7,
          manager: "Alex",
          team_name: "Stairway to Kevin",
          year_joined: "2007",
          seasons: "2",
          status: "Inactive",
          total_pts: "12351",
          total_w: "20",
          total_l: "12",
          games_played: "32",
          playoffs: "2",
          topfour: "0",
          finals: "0",
          titles: "0",
        },
        {
          id: 8,
          manager: "Myles",
          team_name: "Bed, Bath & Biyombo",
          year_joined: "2007",
          seasons: "2",
          status: "Inactive",
          total_pts: "28635",
          total_w: "19",
          total_l: "15",
          games_played: "34",
          playoffs: "2",
          topfour: "1",
          finals: "0",
          titles: "0",
        },
        {
          id: 9,
          manager: "Jordan E.",
          team_name: "The Lone Granger",
          year_joined: "2007",
          seasons: "3",
          status: "Inactive",
          total_pts: "42433",
          total_w: "19",
          total_l: "15",
          games_played: "34",
          playoffs: "3",
          topfour: "0",
          finals: "0",
          titles: "0",
        },
        {
          id: 10,
          manager: "Flittie",
          team_name: "LeBrontosaurus",
          year_joined: "2007",
          seasons: "2",
          status: "Inactive",
          total_pts: "22620",
          total_w: "10",
          total_l: "24",
          games_played: "34",
          playoffs: "1",
          topfour: "0",
          finals: "0",
          titles: "0",
        },
        {
          id: 11,
          manager: "Scott P.",
          team_name: "808's and Fastbreaks",
          year_joined: "2007",
          seasons: "2",
          status: "Inactive",
          total_pts: "11328",
          total_w: "19",
          total_l: "15",
          games_played: "34",
          playoffs: "2",
          topfour: "0",
          finals: "0",
          titles: "0",
        },
        {
          id: 12,
          manager: "Rafa",
          team_name: "P.N.D.B.",
          year_joined: "2008",
          seasons: "9",
          status: "Active",
          total_pts: "174681",
          total_w: "89",
          total_l: "51",
          games_played: "140",
          playoffs: "8",
          topfour: "6",
          finals: "3",
          titles: "2",
        },
        {
          id: 13,
          manager: "Carlo",
          team_name: "Dude Bros",
          year_joined: "2008",
          seasons: "5",
          status: "Inactive",
          total_pts: "68502",
          total_w: "30",
          total_l: "43",
          games_played: "73",
          playoffs: "3",
          topfour: "1",
          finals: "0",
          titles: "0",
        },
        {
          id: 14,
          manager: "Jordan M.",
          team_name: "Coca Scola",
          year_joined: "2008",
          seasons: "1",
          status: "Inactive",
          total_pts: "14341",
          total_w: "10",
          total_l: "8",
          games_played: "18",
          playoffs: "1",
          topfour: "0",
          finals: "0",
          titles: "0",
        },
        {
          id: 15,
          manager: "Danny",
          team_name: "How to Train Your Dragic",
          year_joined: "2008",
          seasons: "3",
          status: "Inactive",
          total_pts: "40148",
          total_w: "15",
          total_l: "30",
          games_played: "45",
          playoffs: "2",
          topfour: "1",
          finals: "0",
          titles: "0",
        },
        {
          id: 16,
          manager: "R. Zettle",
          team_name: "Grand Theft Rondo",
          year_joined: "2008",
          seasons: "1",
          status: "Inactive",
          total_pts: "13881",
          total_w: "5",
          total_l: "13",
          games_played: "18",
          playoffs: "0",
          topfour: "0",
          finals: "0",
          titles: "0",
        },
        {
          id: 17,
          manager: "Rudy",
          team_name: "Rudy Block",
          year_joined: "2009",
          seasons: "3",
          status: "Inactive",
          total_pts: "41517",
          total_w: "18",
          total_l: "24",
          games_played: "32",
          playoffs: "3",
          topfour: "0",
          finals: "0",
          titles: "0",
        },
        {
          id: 18,
          manager: "Edde",
          team_name: "My House Turtles",
          year_joined: "2009",
          seasons: "2",
          status: "Inactive",
          total_pts: "26493",
          total_w: "12",
          total_l: "12",
          games_played: "24",
          playoffs: "1",
          topfour: "1",
          finals: "0",
          titles: "0",
        },
        {
          id: 19,
          manager: "A.J.",
          team_name: "T.I.N.M.",
          year_joined: "2009",
          seasons: "1",
          status: "Inactive",
          total_pts: "12623",
          total_w: "8",
          total_l: "4",
          games_played: "12",
          playoffs: "1",
          topfour: "1",
          finals: "0",
          titles: "0",
        },
        {
          id: 20,
          manager: "Chad",
          team_name: "Biz Markieff",
          year_joined: "2009",
          seasons: "1",
          status: "Inactive",
          total_pts: "9625",
          total_w: "1",
          total_l: "13",
          games_played: "14",
          playoffs: "0",
          topfour: "0",
          finals: "0",
          titles: "0",
        },
        {
          id: 21,
          manager: "Josh",
          team_name: "Team Ale",
          year_joined: "2010",
          seasons: "2",
          status: "Inactive",
          total_pts: "43145",
          total_w: "12",
          total_l: "31",
          games_played: "43",
          playoffs: "1",
          topfour: "0",
          finals: "0",
          titles: "0",
        },
        {
          id: 22,
          manager: "Lamar",
          team_name: "Kyrie on Baggage",
          year_joined: "2010",
          seasons: "7",
          status: "Active",
          total_pts: "101460",
          total_w: "28",
          total_l: "55",
          games_played: "83",
          playoffs: "2",
          topfour: "0",
          finals: "0",
          titles: "0",
        },
        {
          id: 23,
          manager: "Marcco",
          team_name: "Team Zags",
          year_joined: "2010",
          seasons: "1",
          status: "Inactive",
          total_pts: "8864",
          total_w: "1",
          total_l: "11",
          games_played: "12",
          playoffs: "0",
          topfour: "0",
          finals: "0",
          titles: "0",
        },
        {
          id: 24,
          manager: "Kristen",
          team_name: "Team Miguel",
          year_joined: "2010",
          seasons: "1",
          status: "Inactive",
          total_pts: "15394",
          total_w: "10",
          total_l: "2",
          games_played: "12",
          playoffs: "1",
          topfour: "1",
          finals: "1",
          titles: "1",
        },
        {
          id: 25,
          manager: "Paul",
          team_name: "Home Oladipo",
          year_joined: "2011",
          seasons: "1",
          status: "Inactive",
          total_pts: "13092",
          total_w: "4",
          total_l: "12",
          games_played: "16",
          playoffs: "0",
          topfour: "0",
          finals: "0",
          titles: "0",
        },
        {
          id: 26,
          manager: "Langston",
          team_name: "Arcata Rage",
          year_joined: "2011",
          seasons: "1",
          status: "Inactive",
          total_pts: "15409",
          total_w: "7",
          total_l: "9",
          games_played: "16",
          playoffs: "0",
          topfour: "0",
          finals: "0",
          titles: "0",
        },
        {
          id: 27,
          manager: "Kenny",
          team_name: "Chief Badass",
          year_joined: "2011",
          seasons: "1",
          status: "Inactive",
          total_pts: "17342",
          total_w: "11",
          total_l: "5",
          games_played: "16",
          playoffs: "1",
          topfour: "0",
          finals: "0",
          titles: "0",
        },
        {
          id: 28,
          manager: "Matt",
          team_name: "Captain Badass",
          year_joined: "2011",
          seasons: "1",
          status: "Inactive",
          total_pts: "17002",
          total_w: "9",
          total_l: "7",
          games_played: "16",
          playoffs: "1",
          topfour: "1",
          finals: "1",
          titles: "0",
        },
        {
          id: 29,
          manager: "Adam",
          team_name: "Stone Rockz",
          year_joined: "2012",
          seasons: "5",
          status: "Active",
          total_pts: "111468",
          total_w: "36",
          total_l: "14",
          games_played: "50",
          playoffs: "5",
          topfour: "3",
          finals: "3",
          titles: "1",
        },
        {
          id: 30,
          manager: "Jimmy",
          team_name: "Manute Balls",
          year_joined: "2012",
          seasons: "2",
          status: "Inactive",
          total_pts: "31793",
          total_w: "12",
          total_l: "20",
          games_played: "32",
          playoffs: "1",
          topfour: "0",
          finals: "0",
          titles: "0",
        },
        {
          id: 31,
          manager: "Robbie",
          team_name: "James of Thrones",
          year_joined: "2012",
          seasons: "1",
          status: "Inactive",
          total_pts: "16080",
          total_w: "3",
          total_l: "14",
          games_played: "17",
          playoffs: "0",
          topfour: "0",
          finals: "0",
          titles: "0",
        },
        {
          id: 32,
          manager: "Chris",
          team_name: "Toronto Faptors",
          year_joined: "2013",
          seasons: "4",
          status: "Active",
          total_pts: "85841",
          total_w: "25",
          total_l: "25",
          games_played: "50",
          playoffs: "3",
          topfour: "0",
          finals: "0",
          titles: "0",
        },
        {
          id: 33,
          manager: "Zach L.",
          team_name: "Coon & Friends",
          year_joined: "2013",
          seasons: "1",
          status: "Inactive",
          total_pts: "13255",
          total_w: "4",
          total_l: "10",
          games_played: "14",
          playoffs: "0",
          topfour: "0",
          finals: "0",
          titles: "0",
        },
        {
          id: 34,
          manager: "Mark",
          team_name: "K.P.P.M.",
          year_joined: "2013",
          seasons: "1",
          status: "Inactive",
          total_pts: "32766",
          total_w: "9",
          total_l: "6",
          games_played: "15",
          playoffs: "1",
          topfour: "1",
          finals: "0",
          titles: "0",
        },
        {
          id: 35,
          manager: "Jess",
          team_name: "Z Bo",
          year_joined: "2013",
          seasons: "1",
          status: "Inactive",
          total_pts: "13751",
          total_w: "7",
          total_l: "8",
          games_played: "15",
          playoffs: "1",
          topfour: "0",
          finals: "0",
          titles: "0",
        },
        {
          id: 36,
          manager: "Scott M.",
          team_name: "B.T.T.W,",
          year_joined: "2013",
          seasons: "1",
          status: "Inactive",
          total_pts: "10984",
          total_w: "9",
          total_l: "6",
          games_played: "15",
          playoffs: "0",
          topfour: "0",
          finals: "0",
          titles: "0",
        },
        {
          id: 37,
          manager: "Jesse",
          team_name: "Lawson’s Creek",
          year_joined: "2013",
          seasons: "1",
          status: "Inactive",
          total_pts: "14502",
          total_w: "8",
          total_l: "7",
          games_played: "15",
          playoffs: "1",
          topfour: "0",
          finals: "0",
          titles: "0",
        },
        {
          id: 38,
          manager: "Andy",
          team_name: "Mugsy Balls",
          year_joined: "2013",
          seasons: "1",
          status: "Inactive",
          total_pts: "9152",
          total_w: "1",
          total_l: "13",
          games_played: "14",
          playoffs: "0",
          topfour: "0",
          finals: "0",
          titles: "0",
        },
        {
          id: 39,
          manager: "Mateo",
          team_name: "Miami Notorious",
          year_joined: "2014",
          seasons: "1",
          status: "Inactive",
          total_pts: "15230",
          total_w: "3",
          total_l: "13",
          games_played: "16",
          playoffs: "0",
          topfour: "0",
          finals: "0",
          titles: "0",
        },
        {
          id: 40,
          manager: "Burges",
          team_name: "A Team Has No Name",
          year_joined: "2014",
          seasons: "3",
          status: "Active",
          total_pts: "71438",
          total_w: "30",
          total_l: "20",
          games_played: "50",
          playoffs: "3",
          topfour: "1",
          finals: "1",
          titles: "1",
        },
        {
          id: 41,
          manager: "James",
          team_name: "56 Nights",
          year_joined: "2014",
          seasons: "1",
          status: "Inactive",
          total_pts: "14416",
          total_w: "4",
          total_l: "12",
          games_played: "16",
          playoffs: "0",
          topfour: "0",
          finals: "0",
          titles: "0",
        },
        {
          id: 42,
          manager: "Craig",
          team_name: "Pops for Three",
          year_joined: "2014",
          seasons: "3",
          status: "Active",
          total_pts: "75283",
          total_w: "32",
          total_l: "18",
          games_played: "34",
          playoffs: "3",
          topfour: "1",
          finals: "0",
          titles: "0",
        },
        {
          id: 43,
          manager: "Tanner",
          team_name: "S.O.A.B.",
          year_joined: "2014",
          seasons: "2",
          status: "Active",
          total_pts: "33307",
          total_w: "19",
          total_l: "15",
          games_played: "34",
          playoffs: "1",
          topfour: "1",
          finals: "1",
          titles: "0",
        },
        {
          id:44,
          manager: "Kyle",
          team_name: "BBB Balls",
          year_joined: "2015",
          seasons: "2",
          status: "Active",
          total_pts: "34299",
          total_w: "12",
          total_l: "32",
          games_played: "34",
          playoffs: "1",
          topfour: "0",
          finals: "0",
          titles: "0",
        },
        {
          id: 45,
          manager: "Ryan",
          team_name: "SF Gold Diggers",
          year_joined: "2015",
          seasons: "2",
          status: "Active",
          total_pts: "33780",
          total_w: "10",
          total_l: "24",
          games_played: "34",
          playoffs: "0",
          topfour: "0",
          finals: "0",
          titles: "0",
        },
        {
          id: 46,
          manager: "Sean",
          team_name: "Dieng It",
          year_joined: "2016",
          seasons: "1",
          status: "Inactive",
          total_pts: "17886",
          total_w: "9",
          total_l: "7",
          games_played: "16",
          playoffs: "1",
          topfour: "0",
          finals: "0",
          titles: "0",
        },
        {
          id: 47,
          manager: "Jeremy",
          team_name: "DeMars Rover",
          year_joined: "2017",
          seasons: "1",
          status: "Inactive",
          total_pts: "12412",
          total_w: "2",
          total_l: "16",
          games_played: "18",
          playoffs: "0",
          topfour: "0",
          finals: "0",
          titles: "0",
        },

      ]);
    })
};



