exports.seed = function (knex, Promise) {
  // Deletes ALL existing entries
  return knex("managers")
    .del()
    .then(function () {
      // Inserts seed entries
      return knex("managers").insert([
        {
          id: 1,
          manager: "Ben",
          team_name: "Barles Charkley",
          year_joined: "2007",
          seasons: "10",
          status: "Active",
          total_pts: "120000",
          total_w: "150",
          total_l: "50",
          games_played: "200",
          playoffs: "9",
          topfour: "9",
          finals: "4",
          titles: "2",
        },
        {
          id: 2,
          manager: "Jon",
          team_name: "Windy City Champs",
          year_joined: "2007",
          seasons: "10",
          status: "Active",
          total_pts: "110000",
          total_w: "130",
          total_l: "50",
          games_played: "190",
          playoffs: "7",
          topfour: "4",
          finals: "3",
          titles: "2",
        },
        {
          id: 3,
          manager: "Zettle",
          team_name: "Jesus Shuttlesworth",
          year_joined: "2007",
          seasons: "10",
          status: "Inactive",
          total_pts: "",
          total_w: "",
          total_l: "",
          games_played: "",
          playoffs: "",
          topfour: "",
          finals: "",
          titles: "",
        },
        {
          id: 4,
          manager: "Yacine",
          team_name: "Frat So Hard",
          year_joined: "",
          seasons: "",
          status: "Inactive",
          total_pts: "",
          total_w: "",
          total_l: "",
          games_played: "",
          playoffs: "",
          topfour: "",
          finals: "",
          titles: "",
        },
        {
          id: 5,
          manager: "Brady",
          team_name: "H.H.L.D.",
          year_joined: "",
          seasons: "",
          status: "Inactive",
          total_pts: "",
          total_w: "",
          total_l: "",
          games_played: "",
          playoffs: "",
          topfour: "",
          finals: "",
          titles: "",
        },
        {
          id: 6,
          manager: "Breeden",
          team_name: "The Mau5Trap",
          year_joined: "",
          seasons: "",
          status: "Inactive",
          total_pts: "",
          total_w: "",
          total_l: "",
          games_played: "",
          playoffs: "",
          topfour: "",
          finals: "",
          titles: "",
        },
        {
          id: 7,
          manager: "Alex",
          team_name: "Stairway to Kevin",
          year_joined: "",
          seasons: "",
          status: "Inactive",
          total_pts: "",
          total_w: "",
          total_l: "",
          games_played: "",
          playoffs: "",
          topfour: "",
          finals: "",
          titles: "",
        },
        {
          id: 8,
          manager: "Myles",
          team_name: "Bed, Bath & Biyombo",
          year_joined: "",
          seasons: "",
          status: "Inactive",
          total_pts: "",
          total_w: "",
          total_l: "",
          games_played: "",
          playoffs: "",
          topfour: "",
          finals: "",
          titles: "",
        },
        {
          id: 9,
          manager: "Jordan E.",
          team_name: "The Lone Granger",
          year_joined: "",
          seasons: "",
          status: "Inactive",
          total_pts: "",
          total_w: "",
          total_l: "",
          games_played: "",
          playoffs: "",
          topfour: "",
          finals: "",
          titles: "",
        },
        {
          id: 10,
          manager: "Flittie",
          team_name: "LeBrontosaurus",
          year_joined: "",
          seasons: "",
          status: "Inactive",
          total_pts: "",
          total_w: "",
          total_l: "",
          games_played: "",
          playoffs: "",
          topfour: "",
          finals: "",
          titles: "",
        },
        {
          id: 11,
          manager: "Scott P.",
          team_name: "808's and Fastbreaks",
          year_joined: "",
          seasons: "",
          status: "Inactive",
          total_pts: "",
          total_w: "",
          total_l: "",
          games_played: "",
          playoffs: "",
          topfour: "",
          finals: "",
          titles: "",
        },
        {
          id: 12,
          manager: "Rafa",
          team_name: "P.N.D.B.",
          year_joined: "",
          seasons: "",
          status: "Active",
          total_pts: "",
          total_w: "",
          total_l: "",
          games_played: "",
          playoffs: "",
          topfour: "",
          finals: "",
          titles: "",
        },
        {
          id: 13,
          manager: "Carlo",
          team_name: "Dude Bros",
          year_joined: "",
          seasons: "",
          status: "Inactive",
          total_pts: "",
          total_w: "",
          total_l: "",
          games_played: "",
          playoffs: "",
          topfour: "",
          finals: "",
          titles: "",
        },
        {
          id: 14,
          manager: "Jordan M.",
          team_name: "Coca Scola",
          year_joined: "",
          seasons: "",
          status: "Inactive",
          total_pts: "",
          total_w: "",
          total_l: "",
          games_played: "",
          playoffs: "",
          topfour: "",
          finals: "",
          titles: "",
        },
        {
          id: 15,
          manager: "Danny",
          team_name: "How to Train Your Dragic",
          year_joined: "",
          seasons: "",
          status: "Inactive",
          total_pts: "",
          total_w: "",
          total_l: "",
          games_played: "",
          playoffs: "",
          topfour: "",
          finals: "",
          titles: "",
        },
        {
          id: 16,
          manager: "R. Zettle",
          team_name: "Grand Theft Rondo",
          year_joined: "",
          seasons: "",
          status: "Inactive",
          total_pts: "",
          total_w: "",
          total_l: "",
          games_played: "",
          playoffs: "",
          topfour: "",
          finals: "",
          titles: "",
        },
        {
          id: 17,
          manager: "Rudy",
          team_name: "Rudy Block",
          year_joined: "",
          seasons: "",
          status: "Inactive",
          total_pts: "",
          total_w: "",
          total_l: "",
          games_played: "",
          playoffs: "",
          topfour: "",
          finals: "",
          titles: "",
        },
        {
          id: 18,
          manager: "Edde",
          team_name: "My House Turtles",
          year_joined: "",
          seasons: "",
          status: "Inactive",
          total_pts: "",
          total_w: "",
          total_l: "",
          games_played: "",
          playoffs: "",
          topfour: "",
          finals: "",
          titles: "",
        },
        {
          id: 19,
          manager: "A.J.",
          team_name: "T.I.N.M.",
          year_joined: "",
          seasons: "",
          status: "Inactive",
          total_pts: "",
          total_w: "",
          total_l: "",
          games_played: "",
          playoffs: "",
          topfour: "",
          finals: "",
          titles: "",
        },
        {
          id: 20,
          manager: "Chad",
          team_name: "Biz Markieff",
          year_joined: "",
          seasons: "",
          status: "Inactive",
          total_pts: "",
          total_w: "",
          total_l: "",
          games_played: "",
          playoffs: "",
          topfour: "",
          finals: "",
          titles: "",
        },
        {
          id: 21,
          manager: "Josh",
          team_name: "Team Ale",
          year_joined: "",
          seasons: "",
          status: "Inactive",
          total_pts: "",
          total_w: "",
          total_l: "",
          games_played: "",
          playoffs: "",
          topfour: "",
          finals: "",
          titles: "",
        },
        {
          id: 22,
          manager: "Lamar",
          team_name: "Kyrie on Baggage",
          year_joined: "",
          seasons: "",
          status: "Active",
          total_pts: "",
          total_w: "",
          total_l: "",
          games_played: "",
          playoffs: "",
          topfour: "",
          finals: "",
          titles: "",
        },
        {
          id: 23,
          manager: "Marcco",
          team_name: "Team Zags",
          year_joined: "",
          seasons: "",
          status: "Inactive",
          total_pts: "",
          total_w: "",
          total_l: "",
          games_played: "",
          playoffs: "",
          topfour: "",
          finals: "",
          titles: "",
        },
        {
          id: 24,
          manager: "Kristen",
          team_name: "Team Miguel",
          year_joined: "",
          seasons: "",
          status: "Inactive",
          total_pts: "",
          total_w: "",
          total_l: "",
          games_played: "",
          playoffs: "1",
          topfour: "1",
          finals: "1",
          titles: "1",
        },
        {
          id: 25,
          manager: "Paul",
          team_name: "Home Oladipo",
          year_joined: "",
          seasons: "",
          status: "Inactive",
          total_pts: "",
          total_w: "",
          total_l: "",
          games_played: "",
          playoffs: "",
          topfour: "",
          finals: "",
          titles: "",
        },
        {
          id: 26,
          manager: "Langston",
          team_name: "Arcata Rage",
          year_joined: "",
          seasons: "",
          status: "Inactive",
          total_pts: "",
          total_w: "",
          total_l: "",
          games_played: "",
          playoffs: "",
          topfour: "",
          finals: "",
          titles: "",
        },
        {
          id: 27,
          manager: "Kenny",
          team_name: "Chief Badass",
          year_joined: "",
          seasons: "",
          status: "Inactive",
          total_pts: "",
          total_w: "",
          total_l: "",
          games_played: "",
          playoffs: "",
          topfour: "",
          finals: "",
          titles: "",
        },
        {
          id: 28,
          manager: "Matt",
          team_name: "Captain Badass",
          year_joined: "",
          seasons: "",
          status: "Inactive",
          total_pts: "",
          total_w: "",
          total_l: "",
          games_played: "",
          playoffs: "",
          topfour: "",
          finals: "",
          titles: "",
        },
        {
          id: 29,
          manager: "Adam",
          team_name: "Stone Rockz",
          year_joined: "",
          seasons: "",
          status: "Active",
          total_pts: "",
          total_w: "",
          total_l: "",
          games_played: "",
          playoffs: "",
          topfour: "",
          finals: "",
          titles: "",
        },
        {
          id: 30,
          manager: "Jimmy",
          team_name: "Manute Balls",
          year_joined: "",
          seasons: "",
          status: "Inactive",
          total_pts: "",
          total_w: "",
          total_l: "",
          games_played: "",
          playoffs: "",
          topfour: "",
          finals: "",
          titles: "",
        },
        {
          id: 31,
          manager: "Robbie",
          team_name: "James of Thrones",
          year_joined: "",
          seasons: "",
          status: "Inactive",
          total_pts: "",
          total_w: "",
          total_l: "",
          games_played: "",
          playoffs: "",
          topfour: "",
          finals: "",
          titles: "",
        },
        {
          id: 32,
          manager: "Chris",
          team_name: "Toronto Faptors",
          year_joined: "",
          seasons: "",
          status: "Active",
          total_pts: "",
          total_w: "",
          total_l: "",
          games_played: "",
          playoffs: "",
          topfour: "",
          finals: "",
          titles: "",
        },
        {
          id: 33,
          manager: "Zach L.",
          team_name: "Coon & Friends",
          year_joined: "",
          seasons: "",
          status: "Inactive",
          total_pts: "",
          total_w: "",
          total_l: "",
          games_played: "",
          playoffs: "",
          topfour: "",
          finals: "",
          titles: "",
        },
        {
          id: 34,
          manager: "Mark",
          team_name: "K.P.P.M.",
          year_joined: "",
          seasons: "",
          status: "Inactive",
          total_pts: "",
          total_w: "",
          total_l: "",
          games_played: "",
          playoffs: "",
          topfour: "",
          finals: "",
          titles: "",
        },
        {
          id: 35,
          manager: "Jess",
          team_name: "Z Bo",
          year_joined: "",
          seasons: "",
          status: "Inactive",
          total_pts: "",
          total_w: "",
          total_l: "",
          games_played: "",
          playoffs: "",
          topfour: "",
          finals: "",
          titles: "",
        },
        {
          id: 36,
          manager: "Scott M.",
          team_name: "B.T.T.W,",
          year_joined: "",
          seasons: "",
          status: "Inactive",
          total_pts: "",
          total_w: "",
          total_l: "",
          games_played: "",
          playoffs: "",
          topfour: "",
          finals: "",
          titles: "",
        },
        {
          id: 37,
          manager: "Jesse",
          team_name: "Lawson’s Creek",
          year_joined: "",
          seasons: "",
          status: "Inactive",
          total_pts: "",
          total_w: "",
          total_l: "",
          games_played: "",
          playoffs: "",
          topfour: "",
          finals: "",
          titles: "",
        },
        {
          id: 38,
          manager: "Andy",
          team_name: "Mugsy Balls",
          year_joined: "",
          seasons: "",
          status: "Inactive",
          total_pts: "",
          total_w: "",
          total_l: "",
          games_played: "",
          playoffs: "",
          topfour: "",
          finals: "",
          titles: "",
        },
        {
          id: 39,
          manager: "Mateo",
          team_name: "Miami Notorious",
          year_joined: "",
          seasons: "",
          status: "Inactive",
          total_pts: "",
          total_w: "",
          total_l: "",
          games_played: "",
          playoffs: "",
          topfour: "",
          finals: "",
          titles: "",
        },
        {
          id: 40,
          manager: "Burges",
          team_name: "A Team Has No Name",
          year_joined: "",
          seasons: "",
          status: "Active",
          total_pts: "",
          total_w: "",
          total_l: "",
          games_played: "",
          playoffs: "",
          topfour: "",
          finals: "1",
          titles: "1",
        },
        {
          id: 41,
          manager: "James",
          team_name: "56 Nights",
          year_joined: "",
          seasons: "",
          status: "Inactive",
          total_pts: "",
          total_w: "",
          total_l: "",
          games_played: "",
          playoffs: "",
          topfour: "",
          finals: "",
          titles: "",
        },
        {
          id: 42,
          manager: "Craig",
          team_name: "Pops for Three",
          year_joined: "",
          seasons: "",
          status: "Active",
          total_pts: "",
          total_w: "",
          total_l: "",
          games_played: "",
          playoffs: "",
          topfour: "",
          finals: "",
          titles: "",
        },
        {
          id: 43,
          manager: "Tanner",
          team_name: "S.O.A.B.",
          year_joined: "",
          seasons: "",
          status: "Active",
          total_pts: "",
          total_w: "",
          total_l: "",
          games_played: "",
          playoffs: "",
          topfour: "",
          finals: "",
          titles: "",
        },
        {
          id:44,
          manager: "Kyle",
          team_name: "BBB Balls",
          year_joined: "",
          seasons: "",
          status: "Active",
          total_pts: "",
          total_w: "",
          total_l: "",
          games_played: "",
          playoffs: "",
          topfour: "",
          finals: "",
          titles: "",
        },
        {
          id: 45,
          manager: "Ryan",
          team_name: "SF Gold Diggers",
          year_joined: "",
          seasons: "",
          status: "Active",
          total_pts: "",
          total_w: "",
          total_l: "",
          games_played: "",
          playoffs: "",
          topfour: "",
          finals: "",
          titles: "",
        },
        {
          id: 46,
          manager: "Sean",
          team_name: "Dieng It",
          year_joined: "",
          seasons: "",
          status: "Inactive",
          total_pts: "",
          total_w: "",
          total_l: "",
          games_played: "",
          playoffs: "",
          topfour: "",
          finals: "",
          titles: "",
        },
        {
          id: 47,
          manager: "Jeremy",
          team_name: "DeMars Rover",
          year_joined: "",
          seasons: "",
          status: "Inactive",
          total_pts: "",
          total_w: "",
          total_l: "",
          games_played: "",
          playoffs: "",
          topfour: "",
          finals: "",
          titles: "",
        },

      ]);
    })
};



